### ISSUE TITLE
The app doesn't work on F8000

### ISSUE THREAD

**Issue by bmihovski** [nyakaspeter/White-Raven#1]
Hello,

Thank you for the great app.
I really love the idea of jackett integration.
I have tried to run it on my rooted F8000 where Murdock version works.
Unfortunately the app can start but I am getting **root found but the white raven server is not started** error.
Here is my server.init the ip and api token are changed. I have tried all of the combination about jackettaddress (IP, IP + port, protocol + IP + port)

```bash
		nice -n +19 ./"$SERVERNAME" -storagetype="memory" -memorysize="128" -jackettaddress "http://9.15.1.2:9117" -jackettkey "nvacnlpnr4ga" -downrate="$DOWNSPEED" -uprate="$UPSPEED" -background
```
Please let me know how to provide you more logs and thanks.

**Comment by nyakaspeter** [comment]
Hey,

Can you please SSH into your tv and check if the wrserver process is indeed not running (with the `top` command)? If it's not then please check if the permissions for the wrserver executable are correctly set (it needs to have executable permission). Also you can try to run it manually before opening the White Raven widget on your tv. Also, the `-log` parameter can be useful for debugging.

**Comment by bmihovski** [comment]
Thank you, helping me out.
here is the output of the command
```bash
root@tv:/mtd_rwcommon/widgets/user/WhiteRaven/server $ ./wrserver -log
Segmentation fault
```
I realized something was wrong with the binary. So it was my filezilla settings, instead of auto it should be on binary transfer mode. I reuploaded the files and now everything is working.
The format of jackettaddress is like from my example. So I can confirm the addon working great on F8000.
Now this is the output from top
```bash
   99    68 root     S <  1271m124.9   0  7.3 ./exeTV -vdbinder
 9828     1 root     S N   787m 77.3   2  2.3 ./wrserver -storagetype=memory -memorysize=128 -jackettaddress http://9.8.6.2:9117 -jackettkey nvacn -downrate=0 -uprate=0 -background=false
 ```
 One last question what is the pref feral format of jackettaddress value?

**Comment by nyakaspeter** [comment]
Great, I'm happy you found the issue. The Jackett address must be provided with protocol + ip + port, so you did it right. I will clarify this in the documentation.

Btw, I think the magnet links coming from Jackett are broken in the current release (normal torrents work fine). I just fixed that on the develop branch, I will make a new release soon.
