### ISSUE TITLE
Sometimes no playable torrent found, even though present in jackett 

### ISSUE THREAD

**Issue by bmihovski** [nyakaspeter/White-Raven#3]
Hi dev,

I have spotted something interesting.

Some torrents are returning - "No playable torrent found!" even though results are present in jacket
Here is an example https://www.imdb.com/title/tt0092400/?ref_=nv_sr_srsg_0 

Could you check it please, and thanks

**Comment by nyakaspeter** [comment]
What are your configured trackers in Jackett?

**Comment by bmihovski** [comment]
I have these 

![image](https://user-images.githubusercontent.com/4339683/112717781-6b1c1180-8ef7-11eb-81ec-27d8d7ad2916.png)

By the way the piratebay is returning results for this title so it can be in use for testing

![image](https://user-images.githubusercontent.com/4339683/112717834-b7ffe800-8ef7-11eb-8c35-2a23d0c5caaa.png)

In rutracker we have exact name matching like in imdb

![image](https://user-images.githubusercontent.com/4339683/112717899-32306c80-8ef8-11eb-85c5-fba56cdd13e3.png)


Thanks

**Comment by nyakaspeter** [comment]
Think I found the problem, right now the server searches for categories 5030 (TV/SD) and 5040 (TV/HD) but, for example TPB uses the generic TV category (5000) for SD results. I will adjust this in the next release.
