### ISSUE TITLE
Feature/ Visualize results from jackett when no match from imdb

### ISSUE THREAD

**Issue by bmihovski** [nyakaspeter/White-Raven#4]
Hi dev,

I have some crazy idea for feature if possible.
Can we handle the special case when some title is not present in imdb but still can be found from jackett.
In particular this documentary EARTHGEIST THE MOVIE - A WORLD DIVIDED it can be found in jackett only.
So my idea is when there is a match to have a dummy item in the app with watch it now button in this case we can select from the jackett returned results.

Thank you

**Comment by nyakaspeter** [comment]
Good idea, I think this can be done from the server side fairly easily.
